<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160923/1-160923132F9.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/160923/1-160923132F9.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1000";
$z[1][4]['height']="712";
$z[2]=Array("img"," /uploads/allimg/160923/1-160923132G1.jpg ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/160923/1-160923132G1.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1000";
$z[2][4]['height']="712";
$z[3]=Array("img"," /uploads/allimg/160923/1-160923132G2.jpg ",389,535);
$z[3][4]['ddimg']="/uploads/allimg/160923/1-160923132G2.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1000";
$z[3][4]['height']="712";
$z[4]=Array("img"," /uploads/allimg/160923/1-160923132G3.jpg ",537,683);
$z[4][4]['ddimg']="/uploads/allimg/160923/1-160923132G3.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1000";
$z[4][4]['height']="712";
$z[5]=Array("img"," /uploads/allimg/160923/1-160923132G5.jpg ",685,830);
$z[5][4]['ddimg']="/uploads/allimg/160923/1-160923132G5.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="500";
$z[5][4]['height']="707";

?>