<li> <a href="[field:arcurl/]"><img src="[field:picname/]" width="388" height="593"></a>
        <div class="main_list_tit">PHOTO NAME<br>
          <b>[field:title/]</b><span class="fr">[field:pubdate function="MyDate('Y/m/d',@me)"/]</span></div>
        <div class="main_list_txt">
          <h4>PHOTO DESCRIPTION</h4>
          <p style="height:20px; overflow:hidden"></p>
        </div>
        <div><a href="[field:arcurl/]"><img src="/skin/img/main03.jpg"></a></div>
      </li>