<?php
$z[0]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",488,653);
$z[0][4]['typeid']="2,0";
$z[1]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",896,1061);
$z[1][4]['typeid']="3,0";
$z[2]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1307,1476);
$z[2][4]['typeid']="5,6,7,0";
$z[3]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",1701,1866);
$z[3][4]['typeid']="8,0";
$z[4]=Array("channelartlist","\r\n            <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n            ",2091,2256);
$z[4][4]['typeid']="9,0";
$z[5]=Array("global","",2908,2929);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",3051,3077);
$z[6][4]['name']="cfg_dianhua";
$z[7]=Array("type","\r\n        <li><a href=\"[field:typeurl /]\"><img src=\"/skin/img/index_45.jpg\">样片系列</a></li>\r\n        ",3102,3243);
$z[7][4]['typeid']="4";
$z[8]=Array("type","\r\n        <li><a href=\"[field:typeurl /]\"><img src=\"/skin/img/index_46.jpg\">热门活动</a></li>\r\n        ",3253,3394);
$z[8][4]['typeid']="5";
$z[9]=Array("global","",3546,3572);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",3593,3617);
$z[10][4]['name']="cfg_beian";
$z[11]=Array("global","",3777,3798);
$z[11][4]['name']="cfg_qq";
$z[12]=Array("global","",3896,3922);
$z[12][4]['name']="cfg_dianhua";

?>